/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        'background': '#15130d',
        'surface': '#15130d',
        'surface-dim': '#15130d',
        'surface-bright': '#3b3931',
        'surface-container-lowest': '#100e08',
        'surface-container-low': '#1d1c15',
        'surface-container': '#212019',
        'surface-container-high': '#2c2a23',
        'surface-container-highest': '#37352d',
        'surface-variant': '#37352d',
        'on-surface': '#e7e2d7',
        'on-surface-variant': '#e6bdb5',
        'on-background': '#e7e2d7',
        'primary': '#ffb4a5',
        'primary-container': '#cc2200',
        'on-primary': '#640c00',
        'on-primary-container': '#ffe3dd',
        'secondary': '#c8c6c6',
        'secondary-container': '#474747',
        'on-secondary': '#303030',
        'outline': '#ad8881',
        'outline-variant': '#5c403a',
        'soviet-red': '#cc2200',
        'cctv-green': '#1a3a1a',
      },
      fontFamily: {
        'headline-md': ['"Space Mono"', 'monospace'],
        'headline-lg': ['"Space Mono"', 'monospace'],
        'body-md': ['"Courier Prime"', 'Courier New', 'monospace'],
        'body-lg': ['"Courier Prime"', 'Courier New', 'monospace'],
        'label-bold': ['"JetBrains Mono"', 'monospace'],
        'label-sm': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.05em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '1.0', fontWeight: '400' }],
      },
      spacing: {
        'gutter': '16px',
        'margin': '24px',
      },
    },
  },
  plugins: [],
}
